export type IngredientsCategories =
  | "daily"
  | "behavior"
  | "hospital"
  | "medicine"
  | "vaccine"
  | "food";

export const ingredients = {
  behavior: [
    { label: "踏踏", value: 21, active: true, sort: 84, idx: 85 },
    { label: "哭哭", value: 22, active: true, sort: 85, idx: 86 },
    { label: "舔(空氣)", value: 1, active: true, sort: 0, idx: 1 },
    { label: "舔(左前腳)", value: 23, active: true, sort: 86, idx: 87 },
    { label: "舔(左後腳)", value: 24, active: true, sort: 87, idx: 88 },
    { label: "舔(右前腳)", value: 25, active: true, sort: 88, idx: 89 },
    { label: "舔(右後腳)", value: 26, active: true, sort: 89, idx: 90 },
    { label: "看屁股", value: 2, active: false, sort: 1, idx: 2 },
    { label: "聞屁股", value: 3, active: true, sort: 2, idx: 3 },
    { label: "咬腳", value: 5, active: true, sort: 3, idx: 4 },
    { label: "抓左耳", value: 6, active: true, sort: 4, idx: 5 },
    { label: "抓右耳", value: 7, active: true, sort: 5, idx: 6 },
    { label: "抓癢", value: 8, active: true, sort: 6, idx: 7 },
    { label: "抓右臉", value: 9, active: true, sort: 7, idx: 8 },
    { label: "抓左臉", value: 10, active: true, sort: 8, idx: 9 },
  { label: "抓左下巴", value: 11, active: true, sort: 9, idx: 10 },
    { label: "抓右下巴", value: 12, active: true, sort: 10, idx: 11 },
    { label: "抓下巴", value: 13, active: true, sort: 11, idx: 12 },
    { label: "抓身體", value: 14, active: true, sort: 12, idx: 13 },
    { label: "抓左側身體", value: 15, active: true, sort: 13, idx: 14 },
    { label: "抓右側身體", value: 16, active: true, sort: 14, idx: 15 },
    { label: "抓右腋下", value: 17, active: true, sort: 15, idx: 16 },
    { label: "抓左腋下", value: 18, active: true, sort: 16, idx: 17 },
    { label: "撥臉", value: 19, active: true, sort: 17, idx: 18 },
    { label: "洗臉", value: 20, active: true, sort: 18, idx: 19 },
  ],
  daily: [
    { label: "家裡大便", value: 1, active: true, sort: 20, idx: 21 },
    { label: "散步大便", value: 2, active: true, sort: 21, idx: 22 },
    { label: "出門散步(開始)", value: 13, active: true, sort: 22, idx: 23 },
    { label: "出門散步(結束)", value: 14, active: true, sort: 23, idx: 24 },
    { label: "穿鞋", value: 7, active: true, sort: 24, idx: 25 },
    { label: "沒落地", value: 17, active: true, sort: 25, idx: 26 },
    { label: "水泥地", value: 18, active: true, sort: 72, idx: 73 },
    { label: "草地", value: 19, active: true, sort: 73, idx: 74 },
    { label: "刷牙", value: 3, active: true, sort: 26, idx: 27 },
    { label: "爸爸上班", value: 10, active: true, sort: 27, idx: 28 },
    { label: "爸爸下班", value: 11, active: true, sort: 28, idx: 29 },
    { label: "只有爸爸", value: 12, active: true, sort: 29, idx: 30 },
    { label: "家裡洗澡(開始)", value: 4, active: true, sort: 30, idx: 31 },
    { label: "吹毛髮", value: 8, active: true, sort: 31, idx: 32 },
    { label: "家裡洗澡(結束)", value: 9, active: true, sort: 32, idx: 33 },
    { label: "美容洗澡", value: 5, active: true, sort: 33, idx: 34 },
    { label: "剪指甲", value: 6, active: true, sort: 34, idx: 35 },
    { label: "乾洗(身體)", value: 15, active: true, sort: 35, idx: 36 },
    { label: "乾洗(四腳)", value: 16, active: true, sort: 36, idx: 37 },
  ],
  food: [
    {
      label: "ans20 1/2 + 法米納雞肉石榴1/2",
      value: 1,
      active: false,
      sort: 37,
      idx: 38,
    },
    {
      label: "ans20 + 法米納雞肉石榴 (2 :1)",
      value: 2,
      active: false,
      sort: 38,
      idx: 39,
    },
    {
      label: "ans20 + 法米納雞肉石榴 (3 :1)",
      value: 3,
      active: false,
      sort: 39,
      idx: 40,
    },
    { label: "ans20", value: 4, active: false, sort: 40, idx: 41 },
    { label: "地瓜", value: 5, active: true, sort: 41, idx: 42 },
    { label: "法米納雞肉石榴 ", value: 6, active: true, sort: 74, idx: 75 },
    { label: "st23 ", value: 7, active: true, sort: 75, idx: 76 },
    { label: "零食", value: 8, active: true, sort: 76, idx: 77 },
    { label: "起司泥", value: 9, active: true, sort: 77, idx: 78 },
    { label: "法米納羊肉藍莓", value: 11, active: true, sort: 80, idx: 81 },
    { label: "木入森痕淨白", value: 10, active: true, sort: 79, idx: 80 },
    { label: "st25", value: 12, active: true, sort: 82, idx: 83 },
    { label: "優美登藍油", value: 13, active: false, sort: 83, idx: 84 },
  ],
  medicine: [
    { label: "情緒藥", value: 1, active: true, sort: 42, idx: 43 },
    { label: "安適得", value: 9, active: true, sort: 43, idx: 44 },
    { label: "安癢快", value: 2, active: true, sort: 44, idx: 45 },
    { label: "止瀉", value: 3, active: true, sort: 45, idx: 46 },
    { label: "胃乳", value: 5, active: true, sort: 46, idx: 47 },
    { label: "制酸劑", value: 6, active: true, sort: 47, idx: 48 },
    { label: "神經醯胺(噴下巴)", value: 7, active: true, sort: 48, idx: 49 },
    { label: "神經醯胺(身體兩側)", value: 8, active: true, sort: 49, idx: 50 },
    { label: "神經醯胺(四腳)", value: 10, active: true, sort: 50, idx: 51 },
    { label: "神經醯胺(噴耳朵)", value: 24, active: true, sort: 51, idx: 52 },
    { label: "酷斥癢(噴下巴)", value: 11, active: false, sort: 52, idx: 53 },
    { label: "酷斥癢(噴耳朵)", value: 12, active: false, sort: 53, idx: 54 },
    { label: "酷斥癢(身體兩側)", value: 13, active: false, sort: 54, idx: 55 },
    { label: "酷斥癢(四腳)", value: 14, active: false, sort: 55, idx: 56 },
    { label: "潔膚油(指甲)", value: 17, active: true, sort: 56, idx: 57 },
    { label: "潔膚油(下巴)", value: 18, active: true, sort: 57, idx: 58 },
    {
      label: "護膚清潔保濕噴霧(指甲)",
      value: 21,
      active: true,
      sort: 58,
      idx: 59,
    },
    { label: "奈米潔膚露", value: 19, active: true, sort: 59, idx: 60 },
    { label: "入浴湯20ml", value: 20, active: true, sort: 60, idx: 61 },
    { label: "心疥爽", value: 15, active: true, sort: 61, idx: 62 },
    { label: "益百分", value: 16, active: false, sort: 62, idx: 63 },
    { label: "全能狗s", value: 4, active: true, sort: 63, idx: 64 },
    { label: "細菌感染(抑平菌)", value: 22, active: true, sort: 64, idx: 65 },
    { label: "細菌感染(口服藥)", value: 23, active: true, sort: 65, idx: 66 },
    { label: "新耳康", value: 25, active: true, sort: 78, idx: 79 },
    { label: "耳剋癢", value: 26, active: true, sort: 81, idx: 82 },
  ],
  vaccine: [
    { label: "十合一", value: 1, active: true, sort: 66, idx: 67 },
    { label: "狂犬", value: 3, active: true, sort: 67, idx: 68 },
    { label: "萊姆疫苗", value: 2, active: true, sort: 68, idx: 69 },
  ],
  hospital: [
    {
      label: "猩猩狐狸動物醫院(皮膚科)",
      value: 1,
      active: true,
      sort: 69,
      idx: 70,
    },
    { label: "星宇", value: 2, active: true, sort: 70, idx: 71 },
    { label: "阿牛犬貓急診醫院", value: 3, active: true, sort: 71, idx: 72 },
  ],
};
